---

  - name: install packages and roles for the API server of Escholarship's DSpace 7 Pilot
    hosts: pub-ds-api
    become: yes
    become_user: root

    vars:
      - maven_version: '3.6.3'
      - tomcat_version: '9.0.41'
      - tomcat_permissions_production: True
      - tomcat_install_java: False
      - solr_user: solr
      - ansible_remote_tmp: /tmp
      - code_git_repo: https://github.com/eScholarship/DSpace.git
      - code_source_dir: /home/eschol/dspace
      - code_git_branch: eschol-ds7-pilot
      - code_service_user: eschol

# TODO: copy configs for dspace
# TODO: build the checkout using Maven
# TODO: ant fresh_install
# TODO: copy config for tomcat
# TODO: copy Solr cores from /dspace/solr/* to /var/solr/data
# TODO: restart Solr
# TODO: restart Tomcat
# TODO: smoke test

    tasks:
      - name: latest version of all required packages installed
        yum:
          name:
            - ant
            - git
            - ImageMagick
            - ImageMagick-devel
            - ghostscript
          state: latest

    roles:
    - role: make_service_user
    - role: install_java
    - role: set_up_code
    - role: gantsign.maven
    - role: zaxos.tomcat-ansible-role
    - role: solr
    - role: detail_oriented

