---

  - name: install packages and roles for the API server of Escholarship's DSpace 7 Pilot
    hosts: pub-ds-api
    become: yes
    become_user: root

    vars:
      - maven_version: '3.6.3'
      - tomcat_version: '9.0.41'
      - tomcat_permissions_production: True
      - tomcat_install_java: False
      - solr_version: 8.6.3
      - solr_use_java_version_8: False
      - solr_local_keystore: False
      - solr_ssl_configure: False

      - ansible_remote_tmp: /tmp

# FIXME: the Solr role fails on the first try, works on the second, is probably a permissions thing, fix it

# TODO: copy configs for dspace
# TODO: build the checkout using Maven
# TODO: ant fresh_install
# TODO: copy context fragments for tomcat
# TODO: copy config for tomcat
# TODO: copy Solr cores
# TODO: restart Solr
# TODO: restart Tomcat
# TODO: smoke test

    tasks:
      - name: latest version of all required packages installed
        yum:
          name:
            - ant
            - git
          state: latest

    roles:
    - role: make_service_user
# - role: copy_installers
    - role: install_java
    - role: set_up_code
    - role: gantsign.maven
    - role: zaxos.tomcat-ansible-role
    - role: lean_delivery.solr_standalone
