---

- name: create a service user (default is eschol)
  user:
    name: '{{ service_user_name }}'
    password: '{{ service_user_password }}'
    create_home: true
    # groups:
    #   - sudo # requires some tinkering to make work
    state: present

- name: ensure the service user home folder has the correct permissions (because I dunno gremlins I guess)
  file:
    path: '/home/{{ service_user_name }}'
    owner: '{{ service_user_name }}'
    group: '{{ service_user_name }}'
    mode: 01770
